[experiment_config]
results_dir = "results/artifact_evaluation_results/threads_8"
threads = 8
mount_point = "/mnt/pmem"
pm_device = "/dev/pmem0"
iterations = 1
op_count = 15000000
record_count = 15000000
viper_initial_size=64424509440