[experiment_config]
results_dir = "results/artifact-evaluation/"
threads = 1
mount_point = "/mnt/pmem/"
pm_device = "/dev/pmem0"
iterations = 1
op_count = 1000
record_count = 1000
viper_initial_size=1073741824