[package]
name = "metadata_kv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
vstd = "0.0.0-2026-01-25-0057"
proptest = "1.4"
